before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgif-dev libpng-dev zlib1g-dev
language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
after_success: npm run coverage
